language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo add-apt-repository -y ppa:boost-latest/ppa && sudo apt-get update
  - if [[ $CXX == g++ ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [[ $CXX == clang++ ]]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - if [[ $CXX == clang++ ]]; then sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test; fi
  - if [[ $CXX == clang++ ]]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list"; fi
  - if [[ $CXX == clang++ ]]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' >> /etc/apt/sources.list" && sudo apt-get update; fi
  - if [[ $CXX == clang++ ]]; then wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -; fi
  - if [[ $CXX == clang++ ]]; then sudo apt-get update && sudo apt-get install -y clang-3.6 && export CXX="clang++-3.6" CC="clang-3.6"; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then  sudo apt-get update && sudo apt-get install -y liblua5.1-0-dev libzip-dev libpng12-dev libtolua++5.1-dev libbz2-dev libfluidsynth-dev libmikmod2-dev libmng-dev libtheora-dev libvorbis-dev libx11-dev libsdl1.2-dev; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j

after_success:
  - echo "Add Automated Unit Test!!!"